GET http://localhost:8080/users/
###

POST http://localhost:8080/users/
Content-Type: application/json

{
    "first_name":"dempsey",
    "second_name": "palacio tascon",
    "email" : "dempsey.2001@hotmail.com",
    "password" : "testing"
}

###

DELETE  http://localhost:8080/users/6508d12ed3c75549c4bb2d92